[book]
title = "Unicity Orchestrator"
authors = ["Joshua J. Bouw"]
language = "en"
src = "src"

[build]
build-dir = "../target/book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/joshuajbouw/unicity-orchestrator"
edit-url-template = "https://github.com/joshuajbouw/unicity-orchestrator/edit/master/docs/{path}"
site-url = "/unicity-orchestrator/"

[output.html.search]
enable = true
limit-results = 30
boost-hierarchy = 2
